@startuml Administrator-Publish-Book-Sequence-Diagram

actor Administrator
participant "SWP webapp" as SWPWebapp
participant "Content management service" as ContentManagementService

Administrator --> SWPWebapp : Submit request
SWPWebapp --> ContentManagementService : updateBook() 
ContentManagementService --> SWPWebapp : HTTP 200
SWPWebapp --> Administrator : Success message

@enduml