@startuml Editor-Create-Book-Draft-Sequence-Diagram

actor Editor
participant "SWP webapp" as SWPWebapp
participant "Content management service" as ContentManagementService

Editor --> SWPWebapp : Submit form
SWPWebapp --> ContentManagementService : createBook() 
ContentManagementService --> SWPWebapp : HTTP 200
SWPWebapp --> Editor : Success message

@enduml
