@startuml Editor-Delete-Chapter-Draft-Sequence-Diagram

actor Editor
participant "SWP webapp" as SWPWebapp
participant "Content management service" as ContentManagementService

Editor --> SWPWebapp : Submit request
SWPWebapp --> ContentManagementService : deleteChapter() 
ContentManagementService --> SWPWebapp : HTTP 200
SWPWebapp --> Editor : Success message

@enduml
